var TREE_ITEMS = [
 ['Administration','',
    ['기초정보 관리','',
       ['부서조직 관리','../gw/admin/classl.jsp',],
       ['조직직급 관리','../gw/admin/managerRank.jsp',],
       ['사용자 관리','../gw/admin/main.jsp'],
       ['새 사용자 등록','../gw/admin/useri.jsp?j=a'],
    ],
    ['전자결재 관리','',
       ['전자결재 환경구성','../gw/admin/settingApproval.jsp'],
       ['엑세스 권한 구성','../gw/admin/settingYangsic.html'],
    ],
    ['게시판 관리','',
       ['공지게시판 관리','../gw/admin/settingBoard.jsp?tablename=notice_board'],
       ['자유게시판 관리','../gw/admin/settingBoard.jsp?tablename=free_board'],
    ],
    ['그룹웨어 관리','',
       ['일정관리 모듈','../gw/admin/settingSchedule.jsp'],
    ],
    ['기술문서 관리','',
       ['문서 카테고리 관리','../dms/admin/categoryList.jsp'],
       ['임시 엑세스 권한 관리','../dms/admin/authorityRegulate.jsp'],
    ],
    ['제품정보 관리','',
       ['제품분류 관리','../cm/admin/managerGoodsInfo.jsp'],
       ['프로젝트 관리','../cm/admin/ProjectList.jsp'],
    ],
    ['근태 관리','',
       ['휴가잔량 관리','../servlet/GeunTaeServlet?mode=manager_hyuga_day'],
    ],
    ['자원예약 관리','',
       ['차량 관리','../servlet/BookResourceServlet?category=car&mode=list'],
       ['회의실 관리','../servlet/BookResourceServlet?category=meetroom&mode=list'],
       ['교육실 관리','../servlet/BookResourceServlet?category=eduroom&mode=list'],
       ['프로젝트 관리','../servlet/BookResourceServlet?category=projector&mode=list'],
    ],
 ],
];
